repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: detect-private-key

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss, markdown]
        additional_dependencies:
        -   prettier@3.1.0

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
    -   id: eslint
        files: ^app/.*\.(js|jsx|ts|tsx)$
        additional_dependencies:
        -   eslint@8.56.0
        -   @typescript-eslint/parser@6.19.0
        -   @typescript-eslint/eslint-plugin@6.19.0

-   repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
    -   id: golangci-lint
        args: [--timeout=5m] 