services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - VITE_BASE_URL=${VITE_BASE_URL}
    env_file:
      - ./app/.env
    environment:
      VITE_BASE_URL: ${VITE_BASE_URL}
      NODE_ENV: production
    ports:
      - "127.0.0.1:5173:80"
    depends_on:
      - backend
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=D5YNyg1qZuUGYHgrC57ivx2LXasiE1IC
      - DB_NAME=SSPTRBnDjHpKHrESuDkq
      - DB_PORT=5432
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=D5YNyg1qZuUGYHgrC57ivx2LXasiE1IC
      - POSTGRES_DB=SSPTRBnDjHpKHrESuDkq
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
