const DEPTH_IN_METRES = 0.15;
const SQUARE_FOOT_VALUE = 0.092903;
const WIND_BRACING_WEIGHT = 5.49;
const STIFFENER_WEIGHT = 3.77;
const BASE_PLATE_WEIGHT_IN_KGS = 35.33;
const BASE_PLATE_300_MM_WIDTH_IN_METRES = 0.3;
const BASE_PLATE_400_MM_WIDTH_IN_METRES = 0.4;
const LITRES_PER_WEEK = 150;
const RAFTER_RESTRAINTS_WEIGHT = 4.71;
const COLUMN_RESTRAINTS_WEIGHT = 5.41;
const DOOR_DEPTH_IN_METRES = 0.2;
const PURLIN_CLEAT_WEIGHT = 1.4;

export {
  BASE_PLATE_300_MM_WIDTH_IN_METRES,
  BASE_PLATE_400_MM_WIDTH_IN_METRES,
  BASE_PLATE_WEIGHT_IN_KGS,
  COLUMN_RESTRAINTS_WEIGHT,
  DEPTH_IN_METRES,
  DOOR_DEPTH_IN_METRES,
  LITRES_PER_WEEK,
  PURLIN_CLEAT_WEIGHT,
  RAFTER_RESTRAINTS_WEIGHT,
  SQUARE_FOOT_VALUE,
  STIFFENER_WEIGHT,
  WIND_BRACING_WEIGHT,
};
